# Generated by Django 4.1.2 on 2022-10-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created', models.TimeField(auto_now_add=True)),
                ('update', models.TimeField(auto_now=True)),
            ],
        ),
    ]
