# Generated by Django 4.1.2 on 2022-10-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='update',
            new_name='updated',
        ),
    ]
